package:
  name: snpy
  version: 2.5.2

source:
   git_tag: 2.5.2
   git_url: https://github.com/obscode/snpy.git

requirements:
   build:
      - python
      - setuptools
      - numpy
      - gcc

   run:
      - python
      - numpy
      - scipy
      - pymysql
      - matplotlib
      - ipython
      - pymc
      - astropy

test:
   requires:
      - pytest
   source_files:
      - tests
   commands:
      - cd tests; pytest

about:
   home: http://csp.obs.carnegiescience.edu/data/snpy
   license: MIT
   license_file: LICENSE
   summary: A python package for analysis of supernova light-curves.
