{% set version = "2.5.3" %}

package:
  name: snpy
  version: {{ version }}

source:
   git_tag: {{ version }}
   git_url: https://github.com/obscode/snpy.git

requirements:
   build:
      - python
      - setuptools
      - numpy
      - {{ compiler('c') }}
      - {{ compiler('gfortran') }}

   host:
      - python
      - numpy

   run:
      - python
      - scipy
      - pymysql
      - matplotlib
      - ipython
      - scikit-learn
      - astropy

test:
   requires:
      - pytest
   source_files:
      - tests
   commands:
      - cd tests
      - echo $(pwd)
      - echo $(which pytest)
      - pytest

about:
   home: http://csp.obs.carnegiescience.edu/data/snpy
   license: MIT
   license_file: LICENSE
   summary: A python package for analysis of supernova light-curves.
